export const tableDatas = [
  {
    no: "1",
    product: "Samsung Galaxy S24",
    inStock: 50,
    brand: "Samsung",
    createdBy: "Alice",
    createdAt: "2024-11-01",
  },
  {
    no: "2",
    product: "iPhone 15 Pro",
    inStock: 120,
    brand: "Apple",
    createdBy: "Bob",
    createdAt: "2024-11-03",
  },
  {
    no: "3",
    product: "Xiaomi Redmi Note 13",
    inStock: 50,
    brand: "Xiaomi",
    createdBy: "David",
    createdAt: "2024-11-05",
  },
  {
    no: "4",
    product: "Oppo Reno 12",
    inStock: 50,
    brand: "Oppo",
    createdBy: "Sarah",
    createdAt: "2024-11-06",
  },
  {
    no: "5",
    product: "Vivo X100",
    inStock: 30,
    brand: "Vivo",
    createdBy: "Michael",
    createdAt: "2024-11-08",
  },
  {
    no: "6",
    product: "Google Pixel 9",
    inStock: 50,
    brand: "Google",
    createdBy: "Chris",
    createdAt: "2024-11-09",
  },
  {
    no: "7",
    product: "Sony Xperia 5 VI",
    inStock: 50,
    brand: "Sony",
    createdBy: "Emma",
    createdAt: "2024-11-10",
  },
  {
    no: "8",
    product: "Nothing Phone 2a",
    inStock: 20,
    brand: "Nothing",
    createdBy: "Henry",
    createdAt: "2024-11-11",
  },
  {
    no: "9",
    product: "Nothing Phone 2a",
    inStock: 20,
    brand: "Nothing",
    createdBy: "Henry",
    createdAt: "2024-11-11",
  },
  {
    no: "10",
    product: "Nothing Phone 2a",
    inStock: 20,
    brand: "Nothing",
    createdBy: "Henry",
    createdAt: "2024-11-11",
  },
  {
    no: "11",
    product: "Nothing Phone 2a",
    inStock: 20,
    brand: "Nothing",
    createdBy: "Henry",
    createdAt: "2024-11-11",
  },
  {
    no: "12",
    product: "Nothing Phone 2a",
    inStock: 20,
    brand: "Nothing",
    createdBy: "Henry",
    createdAt: "2024-11-11",
  },
];
